In [32]:
import pandas as pd
import time

In [29]:
df = pd.read_excel("/home/andy/Desktop/byjoose_snippets.xlsx")

In [31]:
df.shape

(1822, 6)

In [33]:
start = time.time()
cached_snippets=[]
for i in range(len(df)):
    if len(cached_snippets) ==0:
        print("here")
        cached_snippets.append({"orignal_ids":[df["id"][i]],"speaker":df["speaker"][i],"text":df["text"][i],"from_time":df["from_time"][i],"to_time":df["to_time"][i],"task_id":df["task_id"][i]})
        print(cached_snippets,i)
    else:
        if df["speaker"][i] == cached_snippets[-1]['speaker']:
            cached_snippets[-1]["orignal_ids"].append(df["id"][i])
            cached_snippets[-1]["text"]+=". "+df["text"][i]
            cached_snippets[-1]["to_time"]=df["to_time"][i]
            cached_snippets[-1]["task_id"]=df["task_id"][i]
        else:
            cached_snippets.append({"orignal_ids":[df["id"][i]],"speaker":df["speaker"][i],"text":df["text"][i],"from_time":df["from_time"][i],"to_time":df["to_time"][i],"task_id":df["task_id"][i]})
        
print("Time for making new snippet for 1822 snippets ={}".format(time.time()-start))

here
[{'orignal_ids': [2346505], 'speaker': 'Customer', 'text': 'well water', 'from_time': 5.4, 'to_time': 8.1}] 0
Time for making new snippet for 1822 snippets =0.06855177879333496

In [37]:
new_snippets_df=pd.DataFrame(cached_snippets)

In [38]:
new_snippets_df

,orignal_ids,speaker,text,from_time,to_time
0,"[2346505, 2460199, 2460200, 2460201]",Customer,well water.multipurpose Cooperative Society Li...,5.40,25.95
1,"[2460202, 2460203, 2460495, 2460496, 2460741, ...",Agent,Truecaller.busy busy.music. bhindi Bajar.Hello...,25.71,8.49
2,[2460744],Customer,courses,8.10,9.18
3,"[2460859, 2460980, 2461041, 2461042]",Agent,expensive.discount expensive busy.busy.Thank you.,1.41,12.48
4,[2461090],Customer,busy,0.00,1.77
5,[2461091],Agent,expensive,1.83,5.70
6,[2461092],Customer,expensive,5.22,6.27
7,[2461093],Agent,busy price,5.73,15.00
8,"[2461094, 2461095, 2461096]",Customer,expensive.price.expensive price,8.28,18.96
9,"[2461097, 2461098]",Agent,Hello..Do not working.,35.73,39.78
10,"[2461101, 2461102, 2461103, 2484857]",Customer,"Hello, how are you?.Are you doing?.so sweet.cost",2.70,3.36
11,"[2484858, 2484859]",Agent,it's not.price,3.12,7.47
12,[2484860],Customer,price,7.17,8.19
13,"[2484861, 2484862, 2484863, 2493245]",Agent,Why you wanted?.P6.bol.Hi.,16.62,4.11
14,[2493246],Customer,Hi.,3.30,4.83
15,"[2493247, 2493248]",Agent,cost.appoint,11.25,19.29
16,"[2493249, 2494108, 2494109, 2494110, 2494111, ...",Customer,appointment.price.appointment.appointment.hell...,18.63,2.70
17,"[2494792, 2494793]",Agent,price.price,0.00,13.50
18,[2495654],Customer,price,0.27,2.01
19,[2495708],Agent,price,0.30,1.41
20,[2495709],Customer,price,0.75,2.04
21,"[2495710, 2495904, 2495905, 2495906, 2495907, ...",Agent,expensive.program.price.Yeah..prices at 2000.c...,3.93,7.44
22,[2507962],Customer,you told price,8.88,10.20
23,[2507963],Agent,ekosh,10.47,13.92
24,"[2507964, 2507965]",Customer,expensive.Hi.,24.51,42.27
25,[2507966],Agent,some coding language,85.47,88.62
26,[2508031],Customer,I,10.50,13.68
27,[2508032],Agent,which course,29.97,31.35
28,[2508033],Customer,which coast,30.60,31.86
29,[2508034],Agent,Krishna,31.95,37.53
...,...,...,...,...,...
547,[4369335],Agent,Rangoli of 42% in maths,70.65,73.38
548,[4369336],Customer,What about style?,74.16,76.05
549,[4369337],Agent,science was around 53,77.85,80.55
550,"[4369338, 4369339, 4369340, 4369341]",Customer,Ok ok shut byju's learning app is going to hel...,80.91,99.00
551,"[4369342, 4369343, 4369344]",Agent,Yes. Yes. I want 4 tablet..so my neighbours al...,99.90,108.57
552,[4369345],Customer,"So, what is your birthday?",109.86,112.62
553,"[4369346, 4369347]",Agent,My budget is around..sorry 40k,113.43,118.50
554,"[4369348, 4369349]",Customer,then I will schedule a demo for.is going to co...,121.14,130.50
555,"[4369350, 4369351]",Agent,Sanskrit.I don't know nothing is number so tha...,131.70,142.92
556,[4369352],Customer,Call me anytime.,144.18,147.21
557,"[4369449, 4369450, 4369451, 4369452, 4369453, ...",Agent,"hi, good afternoon and.Harsh Raghav.I am calli...",3.99,36.36
558,[4369455],Customer,I am his father.,36.78,39.69
559,"[4369456, 4369457]",Agent,so much Raghav new like.Is Suraj ko 10% more t...,38.85,48.21
560,[4369458],Customer,"Yes, I will be very happy.",48.69,51.93
561,[4369459],Agent,amazing girls like to ask you few questions,51.66,57.30
562,[4369460],Customer,"Yes, please.",58.08,60.21
563,[4369461],Agent,OK what is percentage previous year?,59.85,63.42
564,[4369462],Customer,Glassdoor report,64.20,67.92
565,[4369463],Agent,Ok and how much did your child score in match?,67.68,72.69
566,[4369464],Customer,Recorded 43%,72.78,76.02
567,[4369465],Agent,Akbarpur science,75.69,77.58
568,[4369466],Customer,67,78.00,80.73
569,"[4369467, 4369468, 4369469, 4369470, 4369471]",Agent,Let's create I am show the byju's learning app...,80.31,101.76
570,[4369472],Customer,data cable,102.21,105.84
571,[4369473],Agent,Ok ok what is your budget?,105.48,108.42
572,[4369474],Customer,full tablet 60000,108.69,115.17
573,"[4369475, 4369476, 4369477, 4369478, 4369479]",Agent,ok.OK then.Do you like me to book an appointme...,114.03,130.92
574,[4369480],Customer,ok,129.84,130.86
575,[4369481],Agent,Have a nice day.,135.45,137.40
576,"[4369482, 4560115]",Customer,Welcome back..model number,135.54,15.78

In [35]:
df

,id,speaker,text,task_id,from_time,to_time
0,2346505,Customer,well water,18208025,5.40,8.10
1,2460199,Customer,multipurpose Cooperative Society Limited,18219184,16.92,19.77
2,2460200,Customer,even number writing,18219184,21.00,23.10
3,2460201,Customer,9916 17021,18219184,23.76,25.95
4,2460202,Agent,Truecaller,18219184,25.71,30.39
5,2460203,Agent,busy busy,18219184,72.48,73.80
6,2460495,Agent,music,18219206,7.11,18.84
7,2460496,Agent,bhindi Bajar,18219206,7.11,18.84
8,2460741,Agent,Hello.,18219226,1.26,3.60
9,2460742,Agent,Hi.,18219226,4.08,6.00
10,2460743,Agent,watch,18219226,6.24,8.49
11,2460744,Customer,courses,18219226,8.10,9.18
12,2460859,Agent,expensive,18219245,1.41,7.71
13,2460980,Agent,discount expensive busy,18219254,1.11,10.65
14,2461041,Agent,busy,18219263,1.95,5.73
15,2461042,Agent,Thank you.,18219263,6.96,12.48
16,2461090,Customer,busy,18219267,0.00,1.77
17,2461091,Agent,expensive,18219267,1.83,5.70
18,2461092,Customer,expensive,18219267,5.22,6.27
19,2461093,Agent,busy price,18219267,5.73,15.00
20,2461094,Customer,expensive,18219267,8.28,11.13
21,2461095,Customer,price,18219267,12.30,13.62
22,2461096,Customer,expensive price,18219267,16.83,18.96
23,2461097,Agent,Hello.,18219267,35.73,37.05
24,2461098,Agent,Do not working.,18219267,38.10,39.78
25,2461101,Customer,"Hello, how are you?",18219276,2.70,3.72
26,2461102,Customer,Are you doing?,18219276,6.99,8.01
27,2461103,Customer,so sweet,18219276,10.08,11.19
28,2484857,Customer,cost,18221271,1.38,3.36
29,2484858,Agent,it's not,18221271,3.12,6.18
...,...,...,...,...,...,...
1792,4369454,Agent,can I know how are you related to Suraj,18345945,31.80,36.36
1793,4369455,Customer,I am his father.,18345945,36.78,39.69
1794,4369456,Agent,so much Raghav new like,18345945,38.85,42.51
1795,4369457,Agent,Is Suraj ko 10% more than body is stored in pr...,18345945,43.08,48.21
1796,4369458,Customer,"Yes, I will be very happy.",18345945,48.69,51.93
1797,4369459,Agent,amazing girls like to ask you few questions,18345945,51.66,57.30
1798,4369460,Customer,"Yes, please.",18345945,58.08,60.21
1799,4369461,Agent,OK what is percentage previous year?,18345945,59.85,63.42
1800,4369462,Customer,Glassdoor report,18345945,64.20,67.92
1801,4369463,Agent,Ok and how much did your child score in match?,18345945,67.68,72.69
1802,4369464,Customer,Recorded 43%,18345945,72.78,76.02
1803,4369465,Agent,Akbarpur science,18345945,75.69,77.58
1804,4369466,Customer,67,18345945,78.00,80.73
1805,4369467,Agent,Let's create I am show the byju's learning app...,18345945,80.31,86.43
1806,4369468,Agent,and learning program provides and,18345945,88.20,91.02
1807,4369469,Agent,Holistic learning experience,18345945,91.59,94.17
1808,4369470,Agent,and,18345945,95.25,96.90
1809,4369471,Agent,Are you interested in the product to the Tabla...,18345945,97.02,101.76
1810,4369472,Customer,data cable,18345945,102.21,105.84
1811,4369473,Agent,Ok ok what is your budget?,18345945,105.48,108.42
1812,4369474,Customer,full tablet 60000,18345945,108.69,115.17
1813,4369475,Agent,ok,18345945,114.03,116.10
1814,4369476,Agent,OK then,18345945,117.24,119.01
1815,4369477,Agent,Do you like me to book an appointment?,18345945,119.07,121.38
1816,4369478,Agent,"Yes, sir. I love you. Meaning your name and",18345945,123.48,127.23
1817,4369479,Agent,You get your tablets.,18345945,129.45,130.92
1818,4369480,Customer,ok,18345945,129.84,130.86
1819,4369481,Agent,Have a nice day.,18345945,135.45,137.40
1820,4369482,Customer,Welcome back.,18345945,135.54,138.09
1821,4560115,Customer,model number,18354477,13.38,15.78